version: "3.7"

services:
  solaredge-exporter:
    expose:
      - 9171
    ports:
      - 9171:9171
    build: .
    environment:
      - API_TOKEN
      - SITE_ID
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    expose:
      - 3000
